### ISSUE TITLE
Documentation for envelope.bin

### ISSUE THREAD

**Issue by Mikestylz** [giantpune/mailboxbomb#1]
What type of file format is envelope.bin, and how was it created?
Instructions on how to create a custom envelope.bin would be very useful. This is the only part of the project that is not documented.

**Comment by giantpune** [comment]
I'm trying to remember, so forgive me if I'm wrong on some of the details.

The messageboard entries can have a U8 archive included inside them.  The image formats inside the archive are the TPL format.  I don't think it matter which of the variants/encodings you use.  For whatever reason, Nintendo used a nested U8 archive for the messageboard.  So in my bin, its a single image inside a U8 archive inside another U8 archive.

The archive that's attached to the message can have any number of different things inside it.  The wii system menu pulls the files out and uses them if they have the correct name.  Some examples of what can be inside are images for the corners, edges, and centers that would make up the paper that appears under a message.  Another thing that may be included is an image for the envelope, which is what is used in this project.

Specifically, I used my own tools written using wiiqt to create the envelope.bin.  There are plenty of open source tools floating around.  You'll need something to create a tpl image, and then something to pack the u8 archives.

**Comment by Mikestylz** [comment]
What kind of archive is the second embedded one?

I was able to open envelope.bin and extract another file called thumbnail_LZ.bin using an open source tool, but no tools recognize thumbnail_LZ.bin as any kind of wii file. What is odd is that thumbnail_LZ.bin contains the magic number for a u8 file, yet no u8/szs tools recognize it. 

Inside of thumbnail_LZ.bin is what appears to be a file b.tpl when viewed through a hex editor, but the contents appear to be hashed. Could thumbnail_LZ.bin be a different kind of archive than u8?

**Comment by leahanderson1** [comment]
thumbnail_LZ.bin uses LZSS compression. basically just compile this c file https://github.com/leahanderson1/lzss/blob/main/lzss.c (i just patched it to work with non-windows operating systems, on windows use the original: https://www.romhacking.net/utilities/826/) and run `./lzss -d thumbnail_LZ.bin`
this overwrites the original file.
it should now work as a normal u8 archive.
it contains the my_LetterS_b.tpl file.
for reference, i uploaded the PNG i got from converting the my_letter file.
here is the `file` output: `my_LetterS_b.tpl.png: PNG image data, 144 x 96, 8-bit/color RGB, non-interlaced`

<img width="144" height="96" alt="Image" src="https://github.com/user-attachments/assets/2c5ed848-d698-4954-bf84-4bba4c51b99d" />

**Comment by gelsik-dev** [comment]
It would be interesting to know how to change Wilbrand's image to a different one.

**Comment by gelsik-dev** [comment]
But how did you do it? I have been trying to change the image constantly for 5 weeks and 2 days with error and error. I created programs with Python to try to get the tpl, to be able to change it with Wimms SZS Tools and then put it in the envelope.bin and compile the program, but it also failed. giantpune told me to see this Issue but I still don't know #8. Please, if you are so kind, can you tell me how you did it?

**Comment by liangchunn** [comment]
Thanks for the pointers @leahanderson1!

I managed to replace the image and got it showing up on my Wii while testing out my [port of Wilbrand in Rust](https://github.com/liangchunn/wilbrand-rust)

I've documented the decode/encode process here if anyone is interested: 
https://github.com/liangchunn/wilbrand-rust/blob/e111691a971ab89feee6b6038f9140be00ed7c3e/docs/envelope.md

![Image](https://github.com/user-attachments/assets/318cd6c2-74e5-4856-b2bd-11e91221c285)

**Comment by leahanderson1** [comment]
well thanks for the reminder to update my comment to specifically mention that you need the original lzss for it to work on windows 
you should probably link https://www.romhacking.net/utilities/826/ in your documentation, as I am not the original author of it. feel free to link mine as the unix version though!

i also made an archive of the tool in case if anyone is having this problem in the future
github wouldn't let me upload it directly so [here's a catbox link](https://files.catbox.moe/f5yjqf.zip)
